name: CI
on:
  workflow_dispatch:
permissions: {}
jobs:
  build:
    permissions:
      contents: read
    name: build-${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: 'ubuntu-24.04'
            platform: 'win32-ia32'
          - os: 'ubuntu-24.04'
            platform: 'win32-x64'
          - os: 'ubuntu-24.04'
            platform: 'win32-arm64v8'
          - os: 'macos-15-intel'
            platform: 'darwin-x64'
          - os: 'macos-15'
            platform: 'darwin-arm64v8'
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          pipx install meson
          brew install automake nasm
      - name: Build ${{ matrix.platform }}
        run: ./build.sh ${{ matrix.platform }}
      - name: Upload ${{ matrix.platform }} artifact
        uses: actions/upload-artifact@v6
        with:
          name: build-${{ matrix.platform }}
          path: '*.tar.gz'
          compression-level: 0
          retention-days: 1
          if-no-files-found: error
